name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t your-dockerhub-username/hello-world-app:latest .
          docker push your-dockerhub-username/hello-world-app:latest

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Deploy to Kubernetes
        run: |
          terraform init
          terraform apply -auto-approve
     